v0.0.4 - Run Test Case

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -21,14 +21,17 @@ jobs:
       uses: actions/checkout@v4
       with:
         repository: DevOpsTeamB2023/DevOps_Oct2023_TeamB_Development
-        path: development
 
     # [Edit] Test Cases
     - name: Use Test Folder
       run: |
-        cd development
-        go test -coverageprofile=report.out ./tdd/...
-        go tool cover -html=report.out
+        go test -v -coverprofile=report.out ./tdd/...
+
+    - name: Upload Coverage Report
+      uses: actions/upload-artifact@v3
+      with:
+        name: TDD Coverage Report
+        path: report.out
 
     # Upload TDD Results in https://app.codecov.io/gh/DevOpsTeamB2023/DevOps_Oct2023_TeamB_Assignment
     - name: Upload coverage reports to Codecov
@@ -46,13 +49,10 @@ jobs:
               message: 'Codecov report available: https://codecov.io/gh/${{ github.repository }}/branch/${{ github.ref }}'
           })
 
-    # Upload test results into as artifact
-    - name: Upload Test Results
-      uses: actions/upload-artifact@v2
-      with: 
-        name: TDD Results
-        path: testresults
-
+    - name: Fail on Upload
+      if: failure()
+      run: exit 1 # Stop workflow on test failure
+      
     # Create Issue for Failed Workflow
     # - if: ${{ failure() }}
     #   name: Create Issue on Failed workflow
@@ -74,17 +74,6 @@ jobs:
       run: |
         ls -la tdd          # List contents
         cat tdd/report.out  # Print contents of report.out
-
-    # [Edit] Create testresults directory and move test results in new directory
-    - name: Create Test Results Folder
-      run: |
-        mkdir testresults
-        if [[ -f tdd/report.out ]]; then    #Check if report exists
-          mv tdd/report.out ./testresults
-        else
-          echo "report.out not found in tdd directory."
-          exit 1 #Exit with an error code
-        fi
     
   Test_Fail:
     name: Test Cases Fail
