v0.0.3 - Modified Pull Request to Create Issue for Workflow Failure

diff --git a/.github/workflows/PullRequest.yml b/.github/workflows/PullRequest.yml
--- a/.github/workflows/PullRequest.yml
+++ b/.github/workflows/PullRequest.yml
@@ -27,7 +27,8 @@ jobs:
           else
             REVIEWERS="koayyiting"
           fi
-          echo "::set-output name=reviewers::$REVIEWERS"
+          echo "REVIEWERS=$REVIEWERS" >> $GITHUB_ENV
+          echo " ${REVIEWERS} " 
 
       # Add Reviewer to Pull Request
       - uses: actions/checkout@v4
@@ -40,32 +41,98 @@ jobs:
           reviewers: ${{ steps.toadd_reviewers.outputs.reviewers }}
           re-request-when-changes-requested: true
 
+      # Create Issue for Failed Workflow
+      - if: ${{ failure() }}
+        name: Create Issue on Failed workflow
+        uses: dacbd/create-issue-action@main
+        with:
+          token: ${{ github.token }}
+          title: Issue - `${{ github.workflow }}` failed.
+          body: |
+            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+            [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
+            Workflow name - `${{ github.workflow }}`
+            Job -           `${{ github.job }}`
+            status -        `${{ job.status }}`
+            assignees: `${{ github.actor }}`
+          assignees: lacsadoshaniahsantiago, koayyiting
+
   Response_Review:
     name: Approve Review and Merge
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request_review'
     steps:
-    # Retrieve Reviews approved
+      # Retrieve Reviews approved
       - name: Get Review Status
         id: get_reviews
         run: |
           PR_NUMBER=${{ github.event.pull_request.number }}
           REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")
+            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews")
 
-          APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | .user.login')
-          echo "::set-output name=approved_reviews::$APPROVED_REVIEWS"
+          if [[ -n "$REVIEWS" ]]; then
+            APPROVED_REVIEWS=0
+          else
+            APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | length')
+          fi
+          echo "APPROVED_REVIEWS=$APPROVED_REVIEWS" >> $GITHUB_ENV
+          echo "${APPROVED_REVIEWS}"
 
+      # Review Request for Changes Workflow
+      - name: Request for Changes
+        if: github.event.review.state == 'changes_requested'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 2
+
+      - name: Get Changed Files
+        if: github.event.review.state == 'changes_requested'
+        id: changed-markdown-files
+        uses: tj-actions/changed-files@v42
+        env:
+          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
+
+      # Create Issue for Request Changes
+      - name: Create Issue for Failed Test
+        if: github.event.review.state == 'changes_requested'
+        uses: dacbd/create-issue-action@main
+        with:
+          token: ${{ github.token }}
+          title: "[REQUEST CHANGES] PR#${{ github.event.pull_request.number }} "
+          body: |
+            **Files Changed -**
+            
+            [${{ steps.changed-markdown-files.outputs.all_changed_files }}](https://github.com/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }}/${{ steps.changed-markdown-files.outputs.all_changed_files }})
+            
+            [View Code on GitHub](https://github.com/${{ github.repository }}/tree/${{ github.event.pull_request.head.ref }})
+            
+            **Comment -**
+            ${{ github.event.review.body }}
+          assignees: ${{ github.event.pull_request.user.login }}
+
+  # Review Approved Workflow
   Merge_Request:
-    if: ${{ needs.Response_Review.outputs.approved_reviews }} >= 1
+    name: Merge Pull Request
     needs: Response_Review
     runs-on: ubuntu-latest
     steps:
+      - uses: actions/checkout@v4
+      - name: Check Status of Review
+        run: |
+          REVIEW_N=${{ env.APPROVED_REVIEWS }}
+          if [[ REVIEW_N -ge 1 ]]; then
+            echo "Approved Reviews Count: ${REVIEW_N}"
+          else
+            echo "There is no approved reviews. Do not continue next steps" 
+            exit 1
+          fi
+      
     # Retrieve Pull Request status of checks
       - uses: actions/checkout@v4
       - name: Get Check Status
-        id: get-status
+        if: ${{ success() }}
         uses: danieldeichfuss/get-status@v0.0.10
+        id: get-status
         with:
           ref: ${{ github.sha }}
           token: ${{ secrets.GITHUB_TOKEN }}
@@ -74,7 +141,7 @@ jobs:
       - uses: actions/checkout@v3
       - name: Label Pull Request as automerge
         uses: actions-ecosystem/action-add-labels@v1
-        if: ${{ steps.get-status.outputs.all-checks-completed == 'true' && steps.get-status.outputs.all-checks-passed == 'true' }} && ${{ startsWith(github.event.comment.body, '/add-labels') }}
+        if: ${{ success() }} && ${{ steps.get-status.outputs.all-checks-completed == 'true' && steps.get-status.outputs.all-checks-passed == 'true' }} && ${{ startsWith(github.event.comment.body, '/add-labels') }}
         with:
           labels: automerge
 
@@ -85,6 +152,5 @@ jobs:
         env:
           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
         with:
-          required_labels: automerge
-          title: ${{ github.event.pull_request.number }} + " pull request merged"
+          merge_commit_message: "${{ github.event.pull_request.number }} - Merged PR#${{ github.event.pull_request.number }} "
           merge_method: merge
